// Generated by https://quicktype.io

export interface DataJSON {
  chapters: Chapter[];
}

export interface Chapter {
  id:               number;
  title:            string;
  intro:            string;
  btn_text:         string;
  btn_link:         string;
  footnote?:        string;
  result_btn_text?: string;
  result_btn_link?: string;
  image?:           string;
  pages?:           Page[];
}

export interface Page {
  page_id:  number;
  text:     string;
  select?:  Select;
  tooltip:  string;
  is_snack: boolean;
  btn_text: string;
  btn_link: string;
}

export interface Select {
  select_id:   number;
  placeholder: string;
  value:       string;
  type:        string;
  options:     Option[];
}

export interface Option {
  label: string;
  value: string;
  link:  string;
}
