import {motion} from 'framer-motion'
import Head from 'next/head'
import Header from './Header'

const variants = {
  hidden: {opacity: 0, x: 0, y: -200},
  enter: {opacity: 1, x: 0, y: 0},
  exit: {opacity: 0, x: 0, y: 100}
}

const Layout = ({ children }) => {
  
  return ( 
    <>
      <Head>
        <title>AST proof</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <motion.div 
        initial='hidden'
        animate='enter'
        exit='exit'
        variants={variants}
        transition={{duration: 1, ease: 'easeInOut'}}
        className='content'> 
        { children }
      </motion.div>
   </>
   )
}
 
export default Layout